# IMAGE CLASSIFICATION KAGGLE

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline
from sklearn.metrics import classification_report,confusion_matrix
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [11]:
data=pd.read_csv("train.csv").as_matrix()
datatest=pd.read_csv("test.csv").as_matrix()

# Training Data

In [11]:
#Train-Test Split
xtrain=data[0:22000,1:]
train_label=data[0:22000,0]
xtest=data[22000:,1:]
actual_label=data[22000:,0]

In [12]:
#Assigning the classifier
clfdt=DecisionTreeClassifier()

#Validation on Testing Data
clfdt.fit(xtrain,train_label)

#Predcitions
predictions=clfdt.predict(xtest)
predictions

array([7, 8, 8, ..., 7, 6, 9], dtype=int64)

In [13]:
#Saving Results to a file
file=pd.DataFrame(predictions)
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_train.csv')

# Accuracy and Confusion Matrix 

In [14]:
#Finding the Accuracy of the model
print(classification_report(actual_label,predictions))

             precision    recall  f1-score   support

          0       0.92      0.91      0.91      1997
          1       0.92      0.94      0.93      2219
          2       0.79      0.81      0.80      1960
          3       0.81      0.77      0.79      2060
          4       0.82      0.84      0.83      1905
          5       0.79      0.78      0.78      1805
          6       0.88      0.85      0.87      1961
          7       0.87      0.88      0.88      2123
          8       0.76      0.77      0.77      1957
          9       0.80      0.81      0.81      2013

avg / total       0.84      0.84      0.84     20000



In [15]:
print(confusion_matrix(actual_label,predictions))

[[1813    3   22   22   12   31   34   10   34   16]
 [   1 2080   26   24   12    7   10   18   33    8]
 [  27   26 1589   64   35   30   40   51   70   28]
 [  22   20   97 1590   22   90   17   47  107   48]
 [   9   16   30   24 1598   20   26   35   40  107]
 [  24   24   32  103   30 1406   57   18   64   47]
 [  27   16   34   13   44   79 1674    3   55   16]
 [   6    9   56   23   26   26    6 1872   21   78]
 [  26   50   75   64   58   53   33   29 1506   63]
 [  11   13   51   38  100   44    7   71   40 1638]]


# Testing Data

In [16]:
#Train-Test split
X_train=data[:,1:]
y_train=data[:,0]
X_test=datatest

# Decision Tree Classifier with Accuracy of 85.628 %

In [18]:
#Assigning the classifier
clftest=DecisionTreeClassifier()

#Validation on Testing Data
clftest.fit(X_train,y_train)
#Predcitions
predictions=clftest.predict(X_test)
predictions

array([2, 2, 9, ..., 3, 9, 2], dtype=int64)

In [19]:
#Saving Results to a file
file=pd.DataFrame(predictions)
file.index+=1
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_test_tree.csv')
#Accuracy of 85.628 %

In [20]:
#Testing how is it working
#d=xtest[10]
#d=d.reshape(28,28)
#plt.imshow(d,cmap='gray')
#print(clfdt.predict([xtest[10]]))

# Random Forest Classifier Accuracy of 93.914 %

In [17]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
predictions=rfc.predict(X_test)

In [18]:
file=pd.DataFrame(predictions)
file.index+=1
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_test_rfc.csv')
#Accuracy of 93.914 %

   # Random Forest Classifier with n_estimtors=100 Accuracy of 96.528 %

In [19]:
rfcn=RandomForestClassifier(n_estimators=100)
rfcn.fit(X_train,y_train)
predictions=rfcn.predict(X_test)

In [20]:
file=pd.DataFrame(predictions)
file.index+=1
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_test_rfcn.csv')
#Accuracy of 96.528 %

# KNN Classifier Accuracy of 96.557 %
Will take atleast half an hour to run

In [6]:
knnc=KNeighborsClassifier(n_neighbors=10)
knnc.fit(X_train,y_train)
predictions=knnc.predict(X_test)

In [8]:
file=pd.DataFrame(predictions)
file.index+=1
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_test_knnc.csv')
# Accuracy of 96.557 %

# Support Vector Machine Classifier Accuracy 11.614 % Worst Case
will take 6 hours on this machine

In [21]:
clfsvm=SVC(C=100,gamma=0.001)

In [ ]:
#clfsvm.fit(X_train,y_train)

In [ ]:
#Predcitions
#predictions=clfsvm.predict(X_test)
#predictions

In [ ]:
file=pd.DataFrame(predictions)
file.index+=1
file.index.name='ImageId'
file.columns=['Label']
file.to_csv('sample_submission_test_svm.csv')
#Accuracy 11.614 %

# Artificial Neural Networks Classification